apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: todo-app
  namespace: flux-system
spec:
  sourceRef:
    kind: GitRepository
    name: aventusm-dwk
  interval: 1m
  path: ./manifests # Path tells where to find the files.
  prune: true # This will make sure that deleting the file will delete the resource
  validation: client